# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Reberth da Silva
tagline:             '{Frontend Developer}'
description:         'Eu sou o Reberth, um desenvolvedor apaixonado por desenvolvimento e conhecer novas tecnologias.'
url:                 http://reberthdasilva.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Reberth da Silva
  url:               https://www.linkedin.com/in/reberth
  email:             reberthdasilva@gmail.com

# Custom vars
version:             1.0.0
